feat: draw board
DoveLiu/gomoku pull request #3
Opened 2023-07-30 10:02 UTC by DoveLiu

五子棋畫面顯示

2023-07-30 10:34 UTC, chengyu914001 commented on frontend/Board.py
> +    def get_Surface(self) -> pygame.Surface:
改一下命名

2023-07-30 10:35 UTC, chengyu914001 commented on frontend/Board.py
> +        pygame.sprite.Sprite.__init__(self)
```suggestion
        super().__init__()
```
這樣就可以了

2023-07-30 10:37 UTC, chengyu914001 commented on frontend/Gui.py
> +        pygame.sprite.Sprite.__init__(self)
一樣用super即可

2023-07-30 10:37 UTC, chengyu914001 commented on main.py
> +pygame.quit()
這邊要沒有包起來

2023-07-30 10:38 UTC, chengyu914001 commented on resource/FrontendConfig.py
> +    GUI_COLOR = '#F0F0F0'
變數命名不好

2023-07-30 10:42 UTC, chengyu914001 commented
python 檔名不要用駝峰，用底線

2023-07-30 16:40 UTC, chengyu914001 requested changes
1

2023-08-03 03:04 UTC, DoveLiu commented
> python 檔名不要用駝峰，用底線

4b7e70e6

2023-08-03 03:06 UTC, DoveLiu commented on frontend/Board.py
> +    def get_Surface(self) -> pygame.Surface:
a70b730b

2023-08-03 03:07 UTC, DoveLiu commented on frontend/Board.py
> +        pygame.sprite.Sprite.__init__(self)
2628ae81

2023-08-03 03:08 UTC, DoveLiu commented on frontend/Gui.py
> +        pygame.sprite.Sprite.__init__(self)
59871688

2023-08-03 03:09 UTC, DoveLiu commented on resource/FrontendConfig.py
> +    GUI_COLOR = '#F0F0F0'
835705bc

2023-08-03 03:10 UTC, DoveLiu commented on main.py
> +pygame.quit()
先main方法，想到更好的做法再改
6755b1d1

2023-08-03 03:59 UTC, DoveLiu commented
> 
更新 board init & get_surface() 方法內變數命名
68137d07

2023-08-03 04:00 UTC, DoveLiu commented
> > 
> 
> 更新 board init & get_surface() 方法內變數命名 [68137d0](https://github.com/DoveLiu/backgammon/commit/68137d070b285adf2b42047601629b17c63da94f)

更新 board 的 draw_star_point 方法變數命名
ff0140c26

2023-08-03 05:17 UTC, DoveLiu commented
> > > 
> > 
> > 
> > 更新 board init & get_surface() 方法內變數命名 [68137d0](https://github.com/DoveLiu/backgammon/commit/68137d070b285adf2b42047601629b17c63da94f)
> 
> 更新 board 的 draw_star_point 方法變數命名 [ff0140c](https://github.com/DoveLiu/backgammon/commit/ff0140c26226dde37de2b2d11fd59ea4c74917d2)

更新 gun 內的變數命名與取得方式
2c21dea49

2023-08-03 05:18 UTC, DoveLiu commented
> > > > 
> > > 
> > > 
> > > 更新 board init & get_surface() 方法內變數命名 [68137d0](https://github.com/DoveLiu/backgammon/commit/68137d070b285adf2b42047601629b17c63da94f)
> > 
> > 
> > 更新 board 的 draw_star_point 方法變數命名 [ff0140c](https://github.com/DoveLiu/backgammon/commit/ff0140c26226dde37de2b2d11fd59ea4c74917d2)
> 
> 更新 gun 內的變數命名與取得方式 [2c21dea](https://github.com/DoveLiu/backgammon/commit/2c21dea493a790f7595f9bcc14dd1c980a2396e7)

更新 棋盤長度變數變數名稱的取名方式
721d353e32

2023-08-03 06:29 UTC, chengyu914001 commented on main.py
> +        dt = clock.tick(60) / 1000
fps ?

2023-08-05 04:45 UTC, DoveLiu commented on main.py
> +pygame.quit()
更新 main 方法，將某些內容移至 gui class

[f778eaa](https://github.com/DoveLiu/backgammon/pull/3/commits/f778eaa6bb993b1cb77b94499420796831ef945c)

2023-08-06 03:38 UTC, DoveLiu commented
> b4cf007

更新用不到的檔案
[b4cf007](https://github.com/DoveLiu/backgammon/pull/3/commits/b4cf007b51052ea2ac20ec4734b96d0d2fd30ce2)

2023-08-06 03:38 UTC, DoveLiu commented
> 753c73c

更新用不到的計算
[753c73c](https://github.com/DoveLiu/backgammon/pull/3/commits/753c73cebab721e7298e0af9d2e10d7439fa1481)

2023-08-06 06:53 UTC, chengyu914001 commented on main.py
> +pygame.quit()
Gui 需改名

2023-08-06 07:10 UTC, chengyu914001 commented on main.py
> +        dt = clock.tick(60) / 1000
fps = 20

2023-08-09 14:11 UTC, DoveLiu commented on main.py
> +pygame.quit()
更新 board 變數

b05e9591

名子'gui -> gomoku_gui
5f6728129

2023-08-12 06:49 UTC, chengyu914001 commented on frontend/gomoku_gui.py
> +class Gomoku_Gui(pygame.sprite.Sprite):
這不用繼承

2023-08-12 06:50 UTC, chengyu914001 commented on frontend/board.py
> +        # ]
需要拿掉

2023-08-12 06:50 UTC, chengyu914001 commented on frontend/board.py
> +        # ]
```suggestion
```

2023-08-12 06:51 UTC, chengyu914001 commented on frontend/board.py
> +        black_circle_width = self.black_circle_width
多此一舉

2023-08-12 06:53 UTC, chengyu914001 commented on frontend/board.py
> +            pygame.draw.circle(surface, black, black_circle_pos_list[i], black_circle_width)
```suggestion
        for black_circle_pos in black_circle_pos_list:
            pygame.draw.circle(surface, black, black_circle_pos, black_circle_width)
```

2023-08-12 07:46 UTC, DoveLiu commented on frontend/gomoku_gui.py
> +class Gomoku_Gui(pygame.sprite.Sprite):
已取消繼承
12b3e6069e

2023-08-13 03:35 UTC, DoveLiu commented on frontend/board.py
> +        black_circle_width = self.black_circle_width
已更新
cc64b398f1

2023-08-13 03:35 UTC, DoveLiu commented on frontend/board.py
> +            pygame.draw.circle(surface, black, black_circle_pos_list[i], black_circle_width)
已更改 for 迴圈 style
1a8c4d38eb

2023-08-13 07:38 UTC, DoveLiu commented on frontend/board.py
> +            pygame.draw.circle(surface, black, black_circle_pos_list[i], black_circle_width)
更改黑色實心 list 清單為 2維陣列
 9659d53022e
 
 變數名優化
 612cbb2339
 
 刪除中文註釋
 aaf09eb551
 
 把 color config 從 class 改 enum
b4864ed00659

2023-08-13 07:57 UTC, chengyu914001 commented on frontend/board.py
> +            pygame.draw.circle(surface, black, black_circle_pos_list[i], black_circle_width)
enum 命名問題

2023-08-13 08:00 UTC, chengyu914001 commented on frontend/gomoku_gui.py
> +    def get_Surface(self) -> pygame.Surface:
命名

2023-08-13 08:10 UTC, DoveLiu commented on frontend/board.py
> +            pygame.draw.circle(surface, black, black_circle_pos_list[i], black_circle_width)
已經新 enum 命名
e6669914626

2023-08-13 08:10 UTC, DoveLiu commented on frontend/gomoku_gui.py
> +    def get_Surface(self) -> pygame.Surface:
已更新
23597c79816

2023-08-13 08:12 UTC, chengyu914001 approved these changes

2023-08-13 08:13 UTC, merged